# Site settings
title: Feedforward Loop
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ramanb.github.io" # the base hostname & protocol for your site
twitter_username: ramanbob
github_username:  ramanb

# Build settings
markdown: kramdown
highlighter: pygments
